"""Provisions and controls one user's own IB Gateway + Executor - the
instantiated systemd units (deploy/ibgateway-live@.service,
deploy/executor@.service), one pair of processes per user, keyed by
user_id (%i in the unit name). Unlike TradingBot's own version of this
module, there is no admin special-case here: the admin trades on their own
account too (see docs/architecture.md), so every user - admin included -
goes through this exact same path.

"Connect" (provision_and_connect) only starts the Gateway process, not the
Executor: mirrors the proven TradingBot flow - IBKR may need a fresh 2FA
approval on THIS user's own phone before the Gateway actually logs in, so
the Executor should only start once status() shows port_listening=True.
"""
from pathlib import Path

from src import db, secrets_store, systemd_util

PROJECT_DIR = Path(__file__).resolve().parent.parent
IBC_DIR = PROJECT_DIR / "deploy" / "ibc"

GATEWAY_UNIT = "ibgateway-live@{user_id}.service"
EXECUTOR_UNIT = "executor@{user_id}.service"

ProvisioningError = systemd_util.SystemctlError


class CredentialsNotSetError(RuntimeError):
    """Raised when a user tries to connect before saving IBKR credentials
    first - see web/app.py's /api/ibkr_credentials."""


def _ibc_config_path(user_id: int) -> Path:
    return IBC_DIR / f"config-{user_id}-live.ini"


def _write_ibc_config(user_id: int, ibkr_username: str, ibkr_password: str, port: int):
    # Regenerated on every Connect click - never hand-edited, so it's
    # always in sync with whatever credentials/port this user has on file
    # right now.
    content = f"""\
# Auto-generated by src/gateway_provisioning.py for user {user_id} (live).
# Regenerated every time this user clicks Connect - do not edit by hand,
# changes will be overwritten on the next Connect.
IbLoginId={ibkr_username}
IbPassword={ibkr_password}
TradingMode=live
OverrideTwsApiPort={port}

AcceptIncomingConnectionAction=accept
AllowBlindTrading=no
ReadOnlyLogin=no
AcceptNonBrokerageAccountWarning=yes
DismissPasswordExpiryWarning=yes
DismissNSEComplianceNotice=yes
ExistingSessionDetectedAction=primary

# IBC can automate the username/password fields but cannot tap "Approve"
# on this user's own phone for a 2FA push - this just controls how long
# IBC waits for that before giving up.
SecondFactorAuthenticationTimeout=180
SecondFactorDevice=IB Key

LogComponents=open
"""
    path = _ibc_config_path(user_id)
    path.write_text(content)
    path.chmod(0o600)


def provision_and_connect(user_id: int):
    """Writes this user's IBC config from their saved credentials and
    starts their Gateway process. Raises CredentialsNotSetError if they
    haven't saved IBKR credentials yet, or ProvisioningError if starting
    the unit fails (most likely the sudoers rules for @-instances haven't
    been installed on this server yet)."""
    creds = db.get_ibkr_credentials(user_id)
    if creds is None:
        raise CredentialsNotSetError("Save your IBKR username and password first.")

    ibkr_username = creds["ibkr_username"]
    ibkr_password = secrets_store.decrypt(creds["ibkr_password_encrypted"])
    port = db.get_or_assign_gateway_port(user_id)

    IBC_DIR.mkdir(parents=True, exist_ok=True)
    _write_ibc_config(user_id, ibkr_username, ibkr_password, port)
    systemd_util.run_privileged("start", GATEWAY_UNIT.format(user_id=user_id))
    db.update_user_settings(user_id, connected=True)


def resume_executor(user_id: int):
    """Starts this user's Executor - call only after status() shows
    port_listening=True (i.e. 2FA has actually been approved and the
    Gateway is really up)."""
    systemd_util.run_privileged("start", EXECUTOR_UNIT.format(user_id=user_id))


def disconnect(user_id: int):
    """Stops the Executor first, then the Gateway - so the Executor never
    sees its Gateway disappear out from under it mid-cycle."""
    systemd_util.run_privileged("stop", EXECUTOR_UNIT.format(user_id=user_id))
    systemd_util.run_privileged("stop", GATEWAY_UNIT.format(user_id=user_id))
    db.update_user_settings(user_id, connected=False)


def status(user_id: int) -> dict:
    port = db.get_or_assign_gateway_port(user_id)
    return {
        "gateway_active": systemd_util.is_active(GATEWAY_UNIT.format(user_id=user_id)),
        "executor_active": systemd_util.is_active(EXECUTOR_UNIT.format(user_id=user_id)),
        "port_listening": systemd_util.port_listening(port),
    }
